### ISSUE TITLE
Incorrect active search notification

### ISSUE THREAD

**Issue by maurizi** [OpenTreeMap/otm-core#2448] opened 2016-01-14 19:15 UTC
We did a search for Bioswales containing a specific type of perrenial plant, and while it did correctly show that there was active search under the more category, it also incorrectly indicated that there was an active planting site search.

**Comment by RickMohr** [comment] 2016-01-15 16:25
I tried many variations of this on the instance where it happened (`testmap0111`) and can't reproduce. Closing.

**Closed by RickMohr** 2016-01-15 16:25 UTC
Labels: bug, in progress, unverified
