### ISSUE TITLE
Manage > Users > Edit Button not working in Google Chrome

### ISSUE THREAD

**Issue by hadleystein1** [OpenTreeMap/otm-core#2571] opened 2016-05-03 14:23 UTC
Attempted to edit a user role in Chrome and could not press the "Edit" button (upper right corner). Was able to successfully make the change in Safari.

![screen shot 2016-05-03 at 10 22 56 am](https://cloud.githubusercontent.com/assets/15219245/14986244/01740212-1119-11e6-8174-4d6089db6099.png)

**Comment by maurizi** [comment] 2016-05-03 15:10
Duplicate of https://github.com/OpenTreeMap/otm-addons/issues/1150

**Closed by maurizi** 2016-05-03 15:10 UTC
