### ISSUE TITLE
Boundary File filtering makes tree/planting sites un-clickable

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-core#2580] opened 2016-05-13 14:59 UTC
Noted by LA Tree Map--when filtering down to a neighborhood (or presumably any set of boundary files), the trees within that neighborhood are correctly summarized but are not clickable.

Try Beverly Hills in LA: https://www.opentreemap.org/latreemap/map/?z=12/34.0825/-118.3997&q=%7B%22mapFeature.geom%22%3A%7B%22IN_BOUNDARY%22%3A%2230798%22%7D%7D

Or China Town North in Philly: https://www.opentreemap.org/phillytreemap/map/?z=15/39.9588/-75.1507&q=%7B%22mapFeature.geom%22%3A%7B%22IN_BOUNDARY%22%3A%2231411%22%7D%7D

**Comment by RickMohr** [comment] 2016-05-16 15:12
Duplicate of #2569, transferring comment there.

**Closed** 2016-05-16 15:14 UTC
Labels: bug
