### ISSUE TITLE
Area of rain garden does not update until page refreshed

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2693] opened 2016-08-03 15:30 UTC
1. I added a rain garden and went to its detail page
2. Edited the rain garden's polygon and saved
3. The area field did not update
4. Refreshed the page and the area updated

**Comment by jwalgran** [comment] 2016-08-03 17:28
Duplicate of #2667

**Closed by jwalgran** 2016-08-03 17:28 UTC
Labels: bug
