### ISSUE TITLE
Address marker does not appear when searching from tree detail page

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2685] opened 2016-07-25 14:43 UTC
The marker does appear when searching from the map page but not if on a tree detail page.

**Comment by maurizi** [comment] 2016-08-25 20:37
An unexpected difficulty in fixing this is that currently we do not carry the address over to the map page when doing an address search from the plot detail page, only the location.

That makes it difficult to distinguish between a location saved after moving the map and a location from an address search.

**Comment by dboyer** [comment] 2016-12-20 19:01
Probably connected to #1123

**Comment by maurizi** [comment] 2017-08-29 14:50
Duplicate of #1123

**Closed by maurizi** 2017-08-29 14:50 UTC
Labels: bug, high, production
