### ISSUE TITLE
Address icon does not display when searching from tree detail page

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-core#2634] opened 2016-06-23 00:54 UTC
Searching for an address produces an icon when searching from the map page:
<img width="1361" alt="screen shot 2016-06-22 at 8 52 16 pm" src="https://cloud.githubusercontent.com/assets/12401491/16288584/54690890-38bb-11e6-812e-5b7bbbefe172.png">
But searching from a tree detail page:
<img width="1361" alt="screen shot 2016-06-22 at 8 52 29 pm" src="https://cloud.githubusercontent.com/assets/12401491/16288585/546a656e-38bb-11e6-846a-3381f013e9eb.png">
While correctly returning to the map, doesn't result in an address icon:
<img width="1361" alt="screen shot 2016-06-22 at 8 52 35 pm" src="https://cloud.githubusercontent.com/assets/12401491/16288583/54678646-38bb-11e6-9cb2-7d77da2bdaed.png">

Test map: https://staging.opentreemap.org/chapelthrill/map/

**Comment by dboyer** [comment] 2017-08-22 14:16
Duplicate of #2685 which has more detail.

**Closed by dboyer** 2017-08-22 14:16 UTC
Labels: bug, low
