### ISSUE TITLE
Staging 2.2 - Species field includes previous species when adding a tree

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2493] opened 2016-02-03 20:23 UTC
Testing in Firefox

1. I added a tree with a species of Austrian pine and selected "I'm done" in the final step
2. I clicked "Add a Tree" and clicked the map to set location
3. When I clicked Next to go to Step 2, the species field on Step 2 had a drop-down suggestion of Austrian Pine (see screenshot)
3. I clicked anywhere on the screen to get rid of the drop-down and the species field autocompleted with Austrian Pine

I duplicated this problem with a different species. Refreshing the whole map got rid of the problem.

![2016_02_03_add_tree_species_autocomplete](https://cloud.githubusercontent.com/assets/516764/12795680/198b4468-ca89-11e5-8bfd-fa5519b5a819.png)

**Comment by maurizi** [comment] 2016-02-03 20:28
Duplicate of https://github.com/OpenTreeMap/otm-addons/issues/1025

**Closed by maurizi** 2016-02-03 20:28 UTC
Labels: unverified
