### ISSUE TITLE
JavaScript error in urlState.js history.onStateChange

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#2783] opened 2016-09-15 19:53 UTC
Add a tree.
Click Next quickly.
If dev tools is set to pause on exceptions, it will stop on the call to `setStateAndPushToApp` call inside the `history.onStateChange` callback function, with:
```
TypeError: Cannot read property 'data' of null at https://staging.opentreemap.org/static/js/treemap/base-f756eac12f7427f80c00.js:59647:54
"Cannot read property 'data' of null"
```

**Comment by RickMohr** [comment] 2016-09-15 19:59
Closing - duplicate of #2784

**Closed by RickMohr** 2016-09-15 19:59 UTC
