### ISSUE TITLE
User number appears in last updated by search

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2959] opened 2017-01-30 01:57 UTC
1. Enter a user name in the "last updated by" search
2. Click search - user name remains
3. Refresh page
4. Open advanced search again
5. User name displays as a number

![screen shot 2017-01-29 at 8 56 06 pm](https://cloud.githubusercontent.com/assets/516764/22410394/8cf35dfc-e665-11e6-8b2c-b0197e06671a.png)

**Comment by dboyer** [comment] 2017-02-01 17:57
Testing on staging on testmap0125second

1. I added a new tree with user account debtest0130
2. I searched for debtest0130 in the last updated by filter
3. Did not see any drop-down results to select a user name
4. Hit enter
5. Page reloaded with all trees rather than search results
6. I refreshed the page
7. Slowly typed deb in the last updated by filter and it suggested nothing
8. Typed debtest and it suggested debtest22
9. Typed debtest0 and I saw suggestions for debtest0130 and debtest0129

I'm not sure if this is an issue with how quickly we suggest user names or something else.

**Comment by RobinIsTheBird** [comment] 2017-02-01 18:57
Sounds like a `bloodhound` caching problem. If so, it's a different issue from the original one.

**Comment by RobinIsTheBird** [comment] 2017-02-01 19:52
Since we're having trouble reproducing this later issue, moving this issue back into review.

**Closed** 2017-02-09 20:15 UTC
Labels: +, bug, medium, tested on staging
