### ISSUE TITLE
Importer: "Cancel Import" doesn't work

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2030] opened 2015-06-02 14:55 UTC
Seen on the development server:

1) Create an instance centered on Edmonton
2) Do a tree import of \\fileshare\users\rmohr\notes\otm\importer\trees10k.csv
3) Once it starts, click "View" and "Cancel Import"

Expected: import is canceled.
Actual: import continues.

**Comment by jwalgran** [comment] 2015-06-02 15:06
This may be a duplicate of https://github.com/OpenTreeMap/otm-core/issues/1980

**Comment by RickMohr** [comment] 2015-06-02 15:34
Let's fix it.

**Closed** 2015-06-18 17:28 UTC
Labels: unverified
