### ISSUE TITLE
Fix "null has no effect" system check warnings

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2237] opened 2015-09-02 17:03 UTC
```
fab vagrant runserver
[localhost] local: cd "." && vagrant ssh-config
[127.0.0.1] Executing task 'runserver'
[127.0.0.1] sudo: /usr/local/otm/env/bin/python manage.py runserver 0.0.0.0:12000
[127.0.0.1] out: Performing system checks...
[127.0.0.1] out:
[127.0.0.1] out: System check identified some issues:
[127.0.0.1] out:
[127.0.0.1] out: WARNINGS:
[127.0.0.1] out: treemap.Instance.boundaries: (fields.W340) null has no effect on ManyToManyField.
[127.0.0.1] out: treemap.Instance.users: (fields.W340) null has no effect on ManyToManyField.
[127.0.0.1] out:
[127.0.0.1] out: System check identified 2 issues (0 silenced).
[127.0.0.1] out: September 02, 2015 - 12:02:08
[127.0.0.1] out: Django version 1.8.2, using settings 'opentreemap.settings'
[127.0.0.1] out: Starting development server at http://0.0.0.0:12000/
[127.0.0.1] out: Quit the server with CONTROL-C.

**Comment by maurizi** [comment] 2015-09-02 17:08
Duplicate of https://github.com/OpenTreeMap/otm-core/issues/2142

**Closed by maurizi** 2015-09-02 17:08 UTC
Labels: contributing, unverified
