### ISSUE TITLE
Trees can be added outside instance bounds

### ISSUE THREAD

**Issue by kdeloach** [OpenTreeMap/otm-core#2619] opened 2016-06-09 22:58 UTC
I noticed this bug when adding a tree on staging.

Although the tree marker appears to be trapped within the bounding box of a map instance, a tree will be added at whichever point your mouse clicks on, even if that point is beyond the instance bounds.

**Comment by jwalgran** [comment] 2016-06-10 15:49
Duplicate of #1662

**Closed by jwalgran** 2016-06-10 15:49 UTC
Labels: bug
