### ISSUE TITLE
User profile: top links incorrect

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#1325] opened 2014-04-24 22:21 UTC
Log in, visit a map, and go to "My Account". The top links are "Explore Trees" and "Add a Tree", but:

* "Explore Trees" should be "Explore Map"
* "Add a Tree" should be "+" if the instance supports resources
* There should be a "Manage" link

**Comment by maurizi** [comment] 2016-01-13 19:22
@dboyer Can we close this since it is working as intended?

**Comment by dboyer** [comment] 2016-01-14 20:04
Yep

**Closed by dboyer** 2016-01-14 20:04 UTC
Labels: contributing, unverified
